from . import help
from . import start 
from . import menyu
from . import baliqlar
from . import back
from . import miqdar
from . import ichimliklar
from . import cola
from . import ikkinchiovqat
from . import ovqatlar2
from . import savat
from . import narxi
from . import delete_pro
from . import admin